language:
- ruby
rvm:
- 2.2.3
addons:
  code_climate:
    repo_token: 1daf3ed2df2eb3622a2ef124110b3d889a1794f6b3f9990e6d4bc5b7cfbc799d
services:
- elasticsearch
before_script:
- npm install -g bower
- bower install
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 10
gemfile:
- Gemfile
install:
- bundle install
deploy:
  provider: heroku
  api_key:
    secure: YbSUlUyyvcpWzQpK9pIMhhEgAxQ6eLgP7p4Knpryrcx2J7sTpYt4pvy239O62Z92IfociR9ycXtAKQMbU8YcO7NpJeLFLcKFcYJe3WeoqfT5+2U2W71XD8B4B/zrd0/Mg5n6qZ5/VXu2c7qChSKl9LNp4Rsugs+jwM9gDNmRHMJvhoUTJKnvei+UX2OtJ0a+mFqcvfAuCJ39/6WnGgGNLKSj1q3dwfQeXdze0QPHjVmnGB0PxgF13YtQpJ6HcuZJGaGyIE2wPgPzTE7JHRtTN48TY672jIRy5UOcdkh5Lg/70IcR4FI856Z+KciPqRSisP6qeAlFFPZniL5up33ivcmA/7roMTSEpwoGmGL/ucJU7DadEWemQtteX9wHQnnCbYtu3FrVrSZ+ax3zIZFEZ6DheB2K1E0TQ+zqnwDg2aZ9bNtxDrfPocM8yEfWes8ilTPWG0x7beADxu5iY8tuseUhZcUVTt7hdhLu/VO3jvagNlwP5Nw6uBy7wH1DCzocMCuimCNB0jiIPBKXNWUI5WQmLkmIIPMOKumrdPksuIThDldOHH6fR9ikzoM1az644ppr15frs7vQi/db2mby3CG9IXuwgMKx4mvJ4JNkivsVkMsGQw/KPp9/IK4EBiOElnG1yyEo95knt106Mej5JSBiVpko0qxCA6AzwNcMLCM=
  app: adopttogether
  on:
    repo: carterdea/adopttogether
notifications:
  slack:
    secure: X7Um693gdvNYLLwtrCi6F1fFYgpuzxDEUtvmB7IWMuZOZgmtWPxbW/eBMU41UPINnb49RvyftR/OjIcVnu5g+6fBllbc0HwdOmXFFS/3w2DwYM2IwBZ+iUhhPCfU2dDYGK/kPXnDRYdf8N1t+5f3Jqa8/d+eFZQINhZsjQkMZ4pLdDHeURqYKM89MG+1Iw4YgdW+FG1yzLJv4FJXy6TiJdiLATBZTfSJcj20UQgKYn9frqX8qlC5tm4daE6INeM5LbCPICqngxg5DxsdgCR4wSYTDw93VUdavOSKVoQNk4UKK6ZHkgrEaRWPqc6mcByL4rQdJ+6s/rS1dJ3ISzOQaUDXDY/rucv7YAfSiGsgrWP23kS0ckBjr2Y7IYp5nL/ExSPogsV0ZStB6nQWBqUhjCtCLvQTmnAxhGA/7xxAeIoeZbSMIc6LaUBFsTNNXRp4b1Ip9g3vfkN/xPvFgkp9cnNXwIkkW1XBPp3HvlVDNvM4S/1sFOskQaOeaYs80/owrM9iLhuQVrQmXcZMGPnoEN4dq6/u5vRzrj3xmfY2p2dl2J2xDAG7hwxei+I2zinUZUvfsWnbFaiUCZNZwbtzGNOSWNkzLtJmk0bTIJfs/rHqw2FDNoI9W0j1Q06qlPkPXcEvyY/IErzrCMu70zFOTHk+qb332oMjfgbn3d0e0c0=
